### ISSUE TITLE
read_ahead_kb: Directory nonexistent

### ISSUE THREAD

**Issue by mausch** [aws/efs-utils#135] opened 2022-05-24 12:42 UTC
On Ubuntu 20.04 , installed efs-utils https://github.com/aws/efs-utils/commit/b1b91c594490d7524fdda71481e2180032405ea7 as described in https://docs.aws.amazon.com/efs/latest/ug/installing-amazon-efs-utils.html#installing-other-distro

```
$ sudo mount -t efs -o tls,iam fs-xxxxxxx.efs.eu-west-1.amazonaws.com /mnt/efs

Mount attempt 1/3 failed due to timeout after 15 sec, wait 0 sec before next attempt.
/bin/sh: 1: cannot create /sys/class/bdi/0:2097372/read_ahead_kb: Directory nonexistent
```

Despite the error mounting is successful.
It would be good to know what this means though!

Many thanks

**Comment by Cappuccinuo** [comment] 2022-05-25 01:12
Hey @mausch ,

Thanks for the report.

The failure won't block the mount, but it will fail to apply a patch that fixing the potential read throughput issue on kernel 5.4+. Background in [this function comments](https://github.com/aws/efs-utils/blob/master/src/mount_efs/__init__.py#L3483-L3490).

It seems that the `/sys/class/bdi/0:2097372` does not exist. For your AMI, can you run the following commands and check the output? Thanks.

```bash
stat -c "%d" /mnt/efs
ls -al /sys/class/bdi/
```

**Comment by Cappuccinuo** [comment] 2022-05-25 08:33
In theory there should be a link to `../../devices/virtual/bdi/0:2097372` in `/sys/class/bdi`. If you remount, would the issue still persist?

**Comment by mausch** [comment] 2022-05-25 08:48
Yes it still persists.

```

$ sudo mount -t efs -o tls,iam fs-3ae3d3f1.efs.eu-west-1.amazonaws.com /mnt/efs
/bin/sh: 1: cannot create /sys/class/bdi/0:1048761/read_ahead_kb: Directory nonexistent

$ ls -al /sys/class/bdi/
total 0
drwxr-xr-x  2 root root 0 Apr 11 09:18 .
drwxr-xr-x 85 root root 0 Apr 11 09:18 ..
lrwxrwxrwx  1 root root 0 Apr 11 09:19 0:173 -> ../../devices/virtual/bdi/0:173
lrwxrwxrwx  1 root root 0 Apr 11 09:19 0:174 -> ../../devices/virtual/bdi/0:174
lrwxrwxrwx  1 root root 0 May 25 09:46 0:441 -> ../../devices/virtual/bdi/0:441
lrwxrwxrwx  1 root root 0 Apr 11 09:18 11:0 -> ../../devices/virtual/bdi/11:0
lrwxrwxrwx  1 root root 0 Apr 11 09:19 252:0 -> ../../devices/virtual/bdi/252:0
lrwxrwxrwx  1 root root 0 Apr 11 09:18 259:0 -> ../../devices/virtual/bdi/259:0
lrwxrwxrwx  1 root root 0 Apr 11 09:18 7:0 -> ../../devices/virtual/bdi/7:0
lrwxrwxrwx  1 root root 0 Apr 11 09:18 7:1 -> ../../devices/virtual/bdi/7:1
lrwxrwxrwx  1 root root 0 Apr 11 09:19 7:10 -> ../../devices/virtual/bdi/7:10
lrwxrwxrwx  1 root root 0 Apr 11 09:19 7:11 -> ../../devices/virtual/bdi/7:11
lrwxrwxrwx  1 root root 0 Apr 11 09:19 7:12 -> ../../devices/virtual/bdi/7:12
lrwxrwxrwx  1 root root 0 Apr 11 09:19 7:13 -> ../../devices/virtual/bdi/7:13
lrwxrwxrwx  1 root root 0 Apr 11 09:19 7:14 -> ../../devices/virtual/bdi/7:14
lrwxrwxrwx  1 root root 0 Apr 11 09:19 7:15 -> ../../devices/virtual/bdi/7:15
lrwxrwxrwx  1 root root 0 Apr 20 14:48 7:16 -> ../../devices/virtual/bdi/7:16
lrwxrwxrwx  1 root root 0 Apr 11 09:18 7:2 -> ../../devices/virtual/bdi/7:2
lrwxrwxrwx  1 root root 0 Apr 11 09:18 7:3 -> ../../devices/virtual/bdi/7:3
lrwxrwxrwx  1 root root 0 Apr 11 09:18 7:4 -> ../../devices/virtual/bdi/7:4
lrwxrwxrwx  1 root root 0 Apr 11 09:18 7:5 -> ../../devices/virtual/bdi/7:5
lrwxrwxrwx  1 root root 0 Apr 11 09:18 7:6 -> ../../devices/virtual/bdi/7:6
lrwxrwxrwx  1 root root 0 Apr 11 09:18 7:7 -> ../../devices/virtual/bdi/7:7
lrwxrwxrwx  1 root root 0 Apr 11 09:19 7:8 -> ../../devices/virtual/bdi/7:8
lrwxrwxrwx  1 root root 0 Apr 11 09:19 7:9 -> ../../devices/virtual/bdi/7:9
lrwxrwxrwx  1 root root 0 Apr 11 09:18 8:0 -> ../../devices/virtual/bdi/8:0
```

Note the dates. It's `0:441` that's being created instead of the expected `0:1048761` apparently.

**Comment by mausch** [comment] 2022-05-25 09:10
```
# stat /mnt/efs
  File: /mnt/efs
  Size: 6144      	Blocks: 8          IO Block: 1048576 directory
Device: 1000b9h/1048761d	Inode: 9534249367436399746  Links: 4
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-12-04 10:50:23.952000000 +0000
Modify: 2020-12-04 10:50:23.952000000 +0000
Change: 2020-12-04 10:50:23.952000000 +0000
 Birth: -
```

**Comment by Cappuccinuo** [comment] 2022-05-26 09:15
Thanks @mausch for running the command. Can we also run following commands in a python3 console?

```bash
import os
os.stat("/mnt/efs")
minor = int(os.stat("/mnt/efs").st_dev & 0xff)
major = int(os.stat("/mnt/efs").st_dev >> 8 & 0xff)
major, minor
```

It will be great if you can provide the results of commands (ignore this step if the mount is still the one mounted yesterday)

```bash
ls -al /sys/class/bdi/
stat /mnt/efs
```

Thanks.

**Comment by mausch** [comment] 2022-05-26 12:51
```
>>> os.stat("/mnt/efs")
os.stat_result(st_mode=16877, st_ino=9534249367436399746, st_dev=1048761, st_nlink=4, st_uid=0, st_gid=0, st_size=6144, st_atime=1607079023, st_mtime=1607079023, st_ctime=1607079023)
>>> minor = int(os.stat("/mnt/efs").st_dev & 0xff)
>>> major = int(os.stat("/mnt/efs").st_dev >> 8 & 0xff)
>>> major, minor
(0, 185)
```

**Comment by Cappuccinuo** [comment] 2022-05-30 07:38
This is a bug in efs-utils that the read_ahead_kb is touched in the wrong place. 

Current logic: Write to `/sys/class/bdi/0:<device_number>/read_ahead_kb`

Correct logic: Write to `/sys/class/bdi/<major>:<minor>/read_ahead_kb`

The major and minor can be derived based on the Linux kernel code [here](https://github.com/torvalds/linux/blob/master/include/linux/kdev_t.h#L48-L49)

Before the issue is fixed in next efs-utils version, the workaround the fix the error message and throughput issue is

1. Disable the optimize feature in `/etc/amazon/efs/efs-utils.conf` by changing `optimize_readahead` to false.

2. Run the following commands
    ```bash
    device_number=$(stat -c '%d' efs-mount-point)
    ((major = ($device_number & 0xFFF00) >> 8))
    ((minor = ($device_number & 0xFF) | (($device_number >> 12) & 0xFFF00)))
    sudo bash -c "echo 15000 > /sys/class/bdi/$major:$minor/read_ahead_kb"
    ```

**Comment by Cappuccinuo** [comment] 2022-06-13 05:07
v1.33.2 is released with the proper fix. Feel free to reopen. Thanks.

**Closed by Cappuccinuo** 2022-06-13 05:07 UTC
Labels: bug

**Comment by jocel1** [comment] 2023-01-04 23:14
Hi!
README.md still mentions 

```$ sudo bash -c "echo read-ahead-value-in-kb > /sys/class/bdi/0:$(stat -c '%d' efs-mount-point)/read_ahead_kb"```

It should be updated accordingly :)
