### ISSUE TITLE
The efs mounting assistant does not support the 'mount - f' option

### ISSUE THREAD

**Issue by yupengwe** [aws/efs-utils#260] opened 2024-12-05 01:30 UTC
The document states: "Test the fstab entry by using the mount command with the' fake 'option alone with the' all 'and' verbose 'options."However, in reality, the efs mount assistant does not support the 'fake' option, and using the 'mount fav' command will actually mount the efs file system to the mount point.Both Chinese and English documents need to be modified.

Doc link:https://docs.amazonaws.cn/efs/latest/ug/mount-fs-auto-mount-update-fstab.html#update-fstab-file
<img width="455" alt="picture1" src="https://github.com/user-attachments/assets/d849aba7-422d-4725-bea3-9e4cb4e95b82">
<img width="388" alt="picture2" src="https://github.com/user-attachments/assets/1371d19f-4115-4578-9bbc-782f2582c072">

**Comment by anthotse** [comment] 2024-12-05 22:26
This is a duplicate of #259

**Closed by anthotse** 2024-12-05 22:26 UTC
